[tool.mypy]
python_version = "3.8"
namespace_packages = true
check_untyped_defs = true
warn_unused_ignores = true
no_implicit_optional = true
show_error_codes = true

[tool.dep_checker]
allowed_unused = [ "numpy",]

[tool.dep_checker.name_mapping]
pymassspec = "pyms"
